language: node_js

notifications:
  email:
    on_success: never
    on_failure: change

node_js: "10"

git:
  depth: 10
  submodules: false

before_install:
  - git submodule update --init

branches:
  only:
    - master

sudo: false

env:
  - CC=clang CXX=clang++ npm_config_clang=1
