image: Visual Studio 2015

environment:
  matrix:
    - nodejs_version: "8"
    - nodejs_version: "10"

platform: x86

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install

test_script:
  - node -e "console.log(`${process.version} ${process.arch} ${process.platform}`)"
  - npm --version
  - npm test

build: off

branches:
  only:
    - master
