language: node_js

notifications:
  email:
    on_success: never
    on_failure: change

node_js: 6

git:
  depth: 10

branches:
  only:
    - master

env:
  - CXX=g++-4.8

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
