language: node_js

notifications:
  email:
    on_success: never
    on_failure: change

node_js: 6

sudo: false

env: NODE_VERSION=4.4.7 CC=clang CXX=clang++ npm_config_clang=1

addons:
  apt:
    packages:
    - build-essential
    - clang-3.3
