language: node_js
dist: trusty

notifications:
  email:
    on_success: never
    on_failure: change

node_js:
  - "10.2.1"

script: ./bin/npm test

git:
  depth: 10

branches:
  only:
    - master

addons:
  apt:
    packages:
      - libsecret-1-dev
      - g++-4.8
    sources:
      - ubuntu-toolchain-r-test

env:
  - CXX=g++-4.8
