version: "{build}"
platform: x64
environment:
  nodejs_version: "6"

install:
  # Get the requested version of Node.js
  - ps: Install-Product node $env:nodejs_version
  - npm install

build_script:
  # Output useful info for debugging.
  - node --version
  - npm --version
  - cd %APPVEYOR_BUILD_FOLDER%
  - npm test

test: off

deploy: off
